### PR TITLE
Up to date animations with updated devdependencies.

### PR DESCRIPTION
**Pull request by SakhirAtwi**
You can merge changes now,

Re-PR of closed #1

### CODE REVIEW

**Comment by SakhirAtwi** [comment]
Damn! I don'd understand why my commits keep on failing on Travis CI, got to dig in more.

**Comment by warengonzaga** [comment]
@SakhirAtwi please check the Travis logs... I see errors in line 79 in JSON...

**Comment by warengonzaga** [comment]
@SakhirAtwi this is the fastest way... can you please remove the node 8 support in the travis.yml?

```yml
language: node_js
node_js:
- "8" --- delete this line... and commit changes
- "7"
- "6"
before_script:
  - npm install -g gulp
script: gulp
```

**Comment by SakhirAtwi** [comment]
Alright.

**Comment by SakhirAtwi** [comment]
@WarenGonzaga do ahead, merge it now, all clear on my side.

**Comment by warengonzaga** [comment]
@SakhirAtwi alright will do it...

**Comment by warengonzaga** [comment]
@SakhirAtwi I will fix the issue in the node...

**Comment by SakhirAtwi** [comment]
@WarenGonzaga Build failed again at node-6 idk why.

**Comment by SakhirAtwi** [comment]
@WarenGonzaga The thing is I'm running node v8 in my laptop the build shouldn't fail with node-8 either.

**Comment by warengonzaga** [comment]
@SakhirAtwi yeah... I will fix this one... will added support for 7,8,9,10 also add support for gulp 4... I remove support for node 6.... :)

**Comment by warengonzaga** [comment]
@SakhirAtwi after that.. will relase the stable version for the animateCSSplugin

**Comment by SakhirAtwi** [comment]
@WarenGonzaga  Alright, I plan on completing the rest of animate.css animations in a day or two max, after that you should update the github pages site of the plugin too and we are all good to go, all animate.css implemented in GSAP,


Cheers.

**Comment by warengonzaga** [comment]
alright @SakhirAtwi thanks... will fix the issues right now... please watch some changes today...

**Comment by warengonzaga** [comment]
@SakhirAtwi always update your copy...

**Comment by warengonzaga** [comment]
@SakhirAtwi I added you as a collaborator for this project.

**Comment by SakhirAtwi** [comment]
@WarenGonzaga Thanks pal :)

**Pull request merged**
